# Generated by Django 5.2 on 2025-04-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('data_de_nascimento', models.DateField()),
                ('numero_telefone', models.CharField(max_length=11, verbose_name='Insira o número de telefone')),
            ],
        ),
    ]
