# Generated by Django 5.2 on 2025-04-11 01:13

import django.db.models.deletion
import secretaria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo_professor', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email_professor', models.EmailField(max_length=50, verbose_name='Email')),
                ('nascimento_professor', models.DateField(verbose_name='Data de Nascimento')),
                ('numero_professor', models.CharField(max_length=11, verbose_name='Número de telefone')),
                ('cpf_professor', models.CharField(max_length=11, unique=True, validators=[secretaria.models.validate_cpf])),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo_responsavel', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email_responsavel', models.EmailField(max_length=50, verbose_name='Email')),
                ('nascimento_responsavel', models.DateField(verbose_name='Data de Nascimento')),
                ('numero_responsavel', models.CharField(max_length=11, verbose_name='Número de telefone')),
                ('cpf_responsavel', models.CharField(max_length=11, null=True, unique=True, validators=[secretaria.models.validate_cpf])),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('data_de_nascimento', models.DateField()),
                ('numero_telefone', models.CharField(max_length=11, verbose_name='Insira o número de telefone')),
                ('cpf_aluno', models.CharField(max_length=11, unique=True, validators=[secretaria.models.validate_cpf])),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='secretaria.responsavel', verbose_name='Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha_a_turma', models.CharField(blank=True, choices=[('1A', '1 ANO A'), ('1B', '1 ANO B'), ('1C', '1 ANO C'), ('2A', '2 ANO A'), ('2B', '2 ANO B'), ('2C', '2 ANO C'), ('3A', '3 ANO A'), ('3B', '3 ANO B'), ('3C', '3 ANO C')], max_length=2)),
                ('descricao_da_turma', models.CharField(choices=[('JG', 'JOGOS DIGITAIS'), ('CN', 'CIÊNCIAS DA NATUREZA'), ('DS', 'DESENVOLVIMENTO DE SISTEMAS'), ('RS', 'REDES DE COMPUTADORES')], max_length=2, verbose_name='Informe o Itinerário da Turma')),
                ('padrinho_da_turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='secretaria.professor', verbose_name='Padrinho da Turma')),
            ],
        ),
    ]
