# Generated by Django 5.2 on 2025-04-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsável',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo_responsavel', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email_responsavel', models.EmailField(max_length=50, verbose_name='Email')),
                ('nascimento_responsavel', models.DateField(verbose_name='Data de Nascimento')),
                ('numero_responsavel', models.CharField(max_length=11, verbose_name='Número de telefone')),
            ],
        ),
    ]
