# Generated by Django 5.2 on 2025-04-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_responsável'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo_professor', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email_professor', models.EmailField(max_length=50, verbose_name='Email')),
                ('nascimento_professor', models.DateField(verbose_name='Data de Nascimento')),
                ('numero_professor', models.CharField(max_length=11, verbose_name='Número de telefone')),
            ],
        ),
    ]
