# Generated by Django 5.2 on 2025-04-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_alter_responsavel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Proferrores'},
        ),
    ]
