# Generated by Django 5.2 on 2025-04-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_alter_aluno_options_alter_professor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
    ]
