# Generated by Django 5.2 on 2025-04-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0005_matter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matter',
            new_name='Materia',
        ),
    ]
