# Generated by Django 5.2 on 2025-04-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0006_rename_matter_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos_alunos/', verbose_name='Documento PDF'),
        ),
    ]
