# Generated by Django 5.2 on 2025-06-11 11:43

import django.db.models.deletion
import secretaria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0007_aluno_documento_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos_alunos/', verbose_name='Anexar Contrato PDF'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(decimal_places=1, max_digits=5, validators=[secretaria.models.validate_nota], verbose_name='Nota')),
                ('nota2', models.DecimalField(decimal_places=1, max_digits=5, validators=[secretaria.models.validate_nota], verbose_name='Nota')),
                ('media_final', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Média Final')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='secretaria.aluno', verbose_name='Aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='secretaria.materia', verbose_name='Matéria')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='secretaria.turma', verbose_name='Turma')),
            ],
        ),
    ]
