# Generated by Django 5.2 on 2025-06-11 12:13

import secretaria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0009_aluno_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='nota1',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota2',
        ),
        migrations.AddField(
            model_name='nota',
            name='nota1bim',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Nota1'),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota2bim',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Nota2'),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota3bim',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Nota3'),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota4bim',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Nota4'),
        ),
    ]
