# Generated by Django 5.2.3 on 2025-06-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0010_remove_nota_nota1_remove_nota_nota2_nota_nota1bim_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nota',
            new_name='Nota1Bim',
        ),
    ]
