# Generated by Django 5.2.3 on 2025-06-12 17:34

import secretaria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0011_rename_nota_nota1bim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota1bim',
            name='nota1bim',
        ),
        migrations.RemoveField(
            model_name='nota1bim',
            name='nota2bim',
        ),
        migrations.RemoveField(
            model_name='nota1bim',
            name='nota3bim',
        ),
        migrations.RemoveField(
            model_name='nota1bim',
            name='nota4bim',
        ),
        migrations.AddField(
            model_name='nota1bim',
            name='atividade1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Atividade1'),
        ),
        migrations.AddField(
            model_name='nota1bim',
            name='atividade2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Atividade2'),
        ),
        migrations.AddField(
            model_name='nota1bim',
            name='prova',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Prova'),
        ),
        migrations.AddField(
            model_name='nota1bim',
            name='simulado',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Simulado'),
        ),
    ]
