# Generated by Django 5.2.3 on 2025-06-12 18:03

import django.db.models.deletion
import secretaria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0012_remove_nota1bim_nota1bim_remove_nota1bim_nota2bim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota1bim',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_1bim', to='secretaria.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='nota1bim',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_1bim', to='secretaria.materia', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='nota1bim',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_1bim', to='secretaria.turma', verbose_name='Turma'),
        ),
        migrations.CreateModel(
            name='Nota2Bim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade1', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Atividade1')),
                ('atividade2', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Atividade2')),
                ('simulado', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Simulado')),
                ('prova', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Prova')),
                ('media_final', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Média Final')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_2bim', to='secretaria.aluno', verbose_name='Aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_2bim', to='secretaria.materia', verbose_name='Matéria')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_2bim', to='secretaria.turma', verbose_name='Turma')),
            ],
        ),
        migrations.CreateModel(
            name='Nota3Bim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade1', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Atividade1')),
                ('atividade2', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Atividade2')),
                ('simulado', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Simulado')),
                ('prova', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Prova')),
                ('media_final', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Média Final')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_3bim', to='secretaria.aluno', verbose_name='Aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_3bim', to='secretaria.materia', verbose_name='Matéria')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_3bim', to='secretaria.turma', verbose_name='Turma')),
            ],
        ),
        migrations.CreateModel(
            name='Nota4Bim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade1', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Atividade1')),
                ('atividade2', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Atividade2')),
                ('simulado', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Simulado')),
                ('prova', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Prova')),
                ('media_final', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[secretaria.models.validate_nota], verbose_name='Média Final')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_4bim', to='secretaria.aluno', verbose_name='Aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_4bim', to='secretaria.materia', verbose_name='Matéria')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_4bim', to='secretaria.turma', verbose_name='Turma')),
            ],
        ),
    ]
