# Generated by Django 5.2.3 on 2025-06-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0013_alter_nota1bim_aluno_alter_nota1bim_materia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='secretaria.professor'),
        ),
    ]
