# Generated by Django 5.2.3 on 2025-06-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0015_evento_mensalidade_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='reponsavel',
            new_name='responsavel',
        ),
    ]
