# Generated by Django 5.2.3 on 2025-06-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0017_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='mes_referente',
            field=models.CharField(choices=[('jan', 'Janeiro'), ('fev', 'Fevereiro'), ('mar', 'Março'), ('abr', 'Abril'), ('mai', 'Maio'), ('jun', 'Junho'), ('jul', 'Julho'), ('ago', 'Agosto'), ('set', 'Setembro'), ('out', 'Outubro'), ('nov', 'Novembro'), ('dez', 'Dezembro')], default='-----', max_length=20),
        ),
    ]
